### ISSUE TITLE
Test on FreeBSD return error!

### ISSUE THREAD

**Issue by emanzx** [jasperes/bash-yaml#12]
Here are the --debug output..

bash test.sh --debug
person_name=("Jonathan")
person_age=("99")
person_email=("jonathan@email.com")
persons__name+=("'Maria'")
persons__age+=("'88'")
persons__email+=("'maria@email.com'")
persons__name+=("\"João\"")
persons__age+=("\"77\"")
persons__email+=("\"joao@email.com\"")
complex_test_simple_obj_attr=("\"value\"")
complex_test_simple_obj_other_attr=("other \"value\"")
complex_test_simple_obj_chaos_list+=("n        attr: value1")
complex_test_simple_obj_chaos_list__otherv+=("value1v")
complex_test_simple_obj_chaos_list__attr+=("value2")
complex_test_simple_obj_chaos_list__otherv+=("\"value2v\"")
complex_test_simple_obj_a_list+=("0")
complex_test_simple_obj_a_list+=("1")
complex_test_simple_obj_a_list+=("2")
complex_test_simple_obj_a_list+=("3")
complex_test_simple_obj_a_list+=("4")
complex_test_simple_obj_a_list+=("5")
complex_test_simple_obj_a_list+=("6")
complex_test_simple_obj_a_list+=("7")
complex_test_simple_obj_a_list+=("8")
complex_test_simple_obj_a_list+=("9")
more_tests_double_dashes=("--ok")
more_tests_dot_start=(".dot")
more_tests_some_propertie=("some-propertie ok!")
more_tests_domain_com=("domain.com ok!")
more_tests_inline_comment=("something")
more_tests_comment_with_hash=("an#hash")
more_tests_hash=("a#hash")
more_tests_single_quotes_hash1=("'a#hash'")
more_tests_single_quotes_hash2=("'a   #hash'")
more_tests_single_quotes_hash3=("'#hi'")
more_tests_single_quotes_comment_in_string=("'a string...'")
more_tests_double_quotes_hash1=("\"a#hash\"")
more_tests_double_quotes_hash2=("\"a   #hash\"")
more_tests_double_quotes_hash3=("\"#hi\"")
more_tests_double_quotes_comment_in_string=("\"a string...\"")
more_tests_a_multi_dash_property=("result-is=OK")
more_tests_a_multi_dot_property=("result.is=OK")
more_tests_a_property_that_has_quite_a_number_of_dashes=("result-is=OK")
more_tests_a_property_that_has_dashes_and_dots=("result-is.absolutely=fine.and-perfect")

Error on execute tests!

**Comment by jasperes** [comment]
Hi @emanzx 

I didn't tested on BSD systems.

I recently updated the script to work on OSX and a problem that  i've seen on your output that was happening on OSX is it wasn't parsing object list attribute inline:

```complex_test_simple_obj_chaos_list+=("n attr: value1")```

Can you test it again?

**Comment by jasperes** [comment]
Closed for no response.
