### ISSUE TITLE
Option to add a prefix to all variables parsed

### ISSUE THREAD

**Issue by ckuenne** [jasperes/bash-yaml#27]
# Description
I have a use case where sometimes I do not want to overwrite already existing variables of the same name. So ideally, I want to have a separate namespace for all the yaml data.
Would it be possible to add an optional prefix to all variables/structs returned? So that in the lower example, the variable would be called e.g. configxy.myvar instead of myvar?

# Yaml file to test

myvar: test
myarray:
  - 1
  - 2

# Operation Sistem
[] Linux

# Bash version
4.4.12(1)-release

**Comment by jasperes** [comment]
Hi, currently the script have argument for prefix:

`create_variables file.yml prefix`

with this example, your variable will be `prefix_myvar`.

**Comment by ckuenne** [comment]
So, I'm using your most current yaml.sh file and I can see that it has this function:
```
parse_yaml() {
local yaml_file=$1
local prefix=$2
...
```

Should work, right?

test.yml:
`myvar: test`

Test 1:

```
source yaml.sh
create_variables test.yml
echo "1: ${myvar}"
echo "2: ${config_myvar}"
```

Result 1:
```
1: test
2:
```

Test 2:

```
source yaml.sh
create_variables test.yml config
echo "1: ${myvar}"
echo "2: ${config_myvar}"
```

Result 2:
```
1:
2:
```

Am I missing something stupid?

**Comment by ckuenne** [comment]
OOoohhhhh, I'm an idiot... You have to give the full prefix including underscore.

create_variables test.yml config_

My bad. Thanks!
