### ISSUE TITLE
Escape dot keys

### ISSUE THREAD

**Issue by leomeih** [jasperes/bash-yaml#3]
It cannot process https://github.com/roots/trellis/blob/master/group_vars/development/wordpress_sites.yml because the key `example.com` cannot be recognized.

Could you please make it work and add a test case using domain name as key?

**Comment by jasperes** [comment]
@HowardMei Its the same problem i have related on Known issues (Can't parse "some-property").

If i fix, the result will be a variable like:

	wordpress_sites_example_com_site_hosts__canonical=("example.test")

Is it what you want?
