### ISSUE TITLE
Fix Shellcheck warnings

### ISSUE THREAD

**Issue by jasperes** [jasperes/bash-yaml#35]
# Description

After change travis to github actions, Shellcheck are warning some issues.

https://github.com/jasperes/bash-yaml/runs/1626353860?check_suite_focus=true

**Comment by daPhipz** [comment]
I will take care of this!

Before I begin, I have a question though. Is there a reason that you use a specific Shellcheck version in `lint.yaml`?
We could do the following:

```bash
sudo apt-get -y update && sudo apt-get -y install shellcheck
find $GITHUB_WORKSPACE -type f -and \( -name "*.sh" \) | xargs shellcheck
```

This grabs the Shellcheck version from the repo and runs it against every `*.sh` file in the project.
What do you think?
