### ISSUE TITLE
list support incomplete

### ISSUE THREAD

**Issue by hgomez-sonarsource** [jasperes/bash-yaml#5]
List didn't seems to works as expected.

I used test/tesh.sh and complex_test_simple_obj_a_list is empty (created by create_variables). 
But parse_yaml report element members

**Comment by jasperes** [comment]
It was my fault.

First, i did not pass correctly all values from variable `complex_test_simple_obj_a_list`to function `test_list`.

Second, on function `test_list`, i was testing it wrong.
