### ISSUE TITLE
Error in parsing when value ends with 's' character 

### ISSUE THREAD

**Issue by gmelekh** [jasperes/bash-yaml#7]
Hi .
If value ends with "s" character it been cut from the result.
for example : if person_name: Jonathans
the result will be Jonathan without 's' at the end.

--
person:
  name: Jonathan
  age: 99
  email: jonathan@email.com

**Comment by jasperes** [comment]
Hi,

I tested it and worked.

**yaml**
```
person:
  name: jonathans
```

**result**
```
person_name=("Jonathans")
```

Can you tell me more how to reproduce? Maybe `file.yml` and `test.sh` content.

**Comment by gmelekh** [comment]
OK.. I found the reason.
It is reproducible on MAC OS only.
Checked on Ubuntu / CentOS  - all is working

**Comment by DeLaGuardo** [comment]
`sed` tool works differently on Mac OS. GNU version doesn't have this issue. 
`brew install gnu-sed --with-default-names` should fix it for your Mac OS

**Comment by v1k0d3n** [comment]
i think it's safe to close this out, now that the issue has been caught (with a resolution)? we've encountered the same thing on macos systems, and using `--with-default-names` works perfectly.

**Comment by jasperes** [comment]
Maybe a best support for macos, currently i'm not testing on this system.
I'll close this issue. For those who need to fix it, must use `--with-default-names`, as mentioned here.
