### ISSUE TITLE
Error with url value

### ISSUE THREAD

**Issue by gigaga** [jasperes/bash-yaml#9]
Hi,

From the following YAML file:
`servers:
- url: http://test.com`

I get the error //yaml.sh: eval: line 42: syntax error near unexpected token `"url: http://test.com"'

**Comment by jasperes** [comment]
Hi @gigaga,

It's a know issue. You must do like this:

```
servers:
  -
    url: http://test.com
```

Otherwise, `url: http://test.com` will be a string item from `servers` list.

From your example: `[ "${servers[0]}" = "url: http://teste.com" ]`
From my example: `[ "${servers__url[0]}" = "http://teste.com" ]`

**Comment by gigaga** [comment]
Ok but I can't. It is a YAML file generated :(
